version: "2"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - go mod verify
      - task: install-hooks
  test:
    desc: Run all tests
    cmds:
      - go test ./... --cover
  format:
    desc: Format Go code
    cmds:
      - go fmt .
  check:
    desc: Check code quality
    cmds:
      - go vet .
  demo:
    desc: See captainslog in action
    cmds:
      - go run ./demo
  install-hooks:
    desc: Setup Git hooks
    cmds:
      - |
        for file in $(ls hooks/*);
        do 
          filename="${file##*/}";
          basename="${filename%.*}";
          mkdir -p .git/hooks/;
          cp $file .git/hooks/$basename;
          chmod +x .git/hooks/$basename;
        done
