name: Publish Package
on:
  push:
    tags:
      - v* # run on version tags, e.g. v2.0.0
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Powershell
        run: |
            wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo add-apt-repository -y universe
            sudo apt-get install -y powershell
    
      - name: Submit to go.dev
        shell: pwsh
        run: |
            $version=($env:GITHUB_REF -Split '/')[-1]
            Invoke-WebRequest -Uri "http://proxy.golang.org/github.com/vincentfiestada/captainslog/v2/@v/${version}.zip"
