name: Unit Tests
on: [push]
jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Task
        run: curl -sL https://taskfile.dev/install.sh | sh

      - name: Get dependencies
        run: ./bin/task install

      - name: Run tests
        run: ./bin/task test
