name: Unit Tests
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Powershell
        run: |
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https software-properties-common
            wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo add-apt-repository -y universe
            sudo apt-get install -y powershell
    
      - name: Install Go
        shell: pwsh
        run: |
            sudo add-apt-repository -y ppa:longsleep/golang-backports
            sudo apt-get update
            sudo apt-get install -y golang-1.15
            $env:GO111MODULE = "on";

      - name: Run tests
        shell: pwsh
        run: |
            Import-Module ./tasks.psm1;
            Install-Project;
            Invoke-Tests;