name: Unit Tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Task
        run: go get -u -v github.com/go-task/task/cmd/task

      - name: Get dependencies
        run: task install

      - name: Run tests
        run: task test
